spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/dsscheudler?useUnicode=true&characterEncoding=utf8&autoReconnect=true
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        #初始化连接数量，最大最小连接数
        initialSize: 5
        maxActive: 10
        minIdle: 3
        #获取连接等待超时的时间
        maxWait: 600000
        #超过时间限制是否回收
        removeAbandoned: true
        #超过时间限制多长
        removeAbandonedTimeout: 180
        #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 600000
        #配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        #用来检测连接是否有效的sql，要求是一个查询语句
        validationQuery: SELECT 1 FROM DUAL
        #申请连接的时候检测
        testWhileIdle: true
        #申请连接时执行validationQuery检测连接是否有效，配置为true会降低性能
        testOnBorrow: false
        #归还连接时执行validationQuery检测连接是否有效，配置为true会降低性能
        testOnReturn: false
        #打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 50
        #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
        #监控统计用的filter:stat 日志用的filter:log4j 防御SQL注入的filter:wall
        filters: stat

mybatis:
  mapperLocations: classpath*:club.super13.ds.mapping.*.xml
  typeAliasesPackage: club.super13.ds.model
 
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql

server:
  port: 9800





